# -*- coding: utf-8 -*-
"""Capstone Project 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ALb7bTQMJ4aueutz5TCyvI7fWjO8N6ap
"""

# Capstone Project Modul 1
# Database Nilai Ujian Siswa SD Tadika Mesra

# Daftar Nilai Awal

daftar_nilai = [
    {
        'nis' : 19001,
        'nama' : 'Alif',
        'bahasa_indonesia' : 90,
        'matematika' : 90,
        'ipa' : 90
    },
    {
        'nis' : 19002,
        'nama' : 'Budi',
        'bahasa_indonesia' : 90,
        'matematika' : 90,
        'ipa' : 90
    },
    {
        'nis' : 19003,
        'nama' : 'Caca',
        'bahasa_indonesia' : 90,
        'matematika' : 90,
        'ipa' : 90
    }
]

# Function READ (Menampilkan Data Nilai Ujian Siswa) 
# ==================================================

def menu_data_siswa():

    print('''
    ===============================================================
    ----------------- Menu Data Nilai Ujian Siswa -----------------
    |-- Pilihan Menu:
        1. Tampilkan Nilai Ujian Seluruh Siswa
        2. Cari Nilai Ujian Siswa Tertentu
        3. Kembali Ke Menu Utama
    ===============================================================''')
    pilihan_menu = input('''
    Silahkan Pilih Menu (1-3): ''')
    if pilihan_menu == '1':
        data_seluruh_siswa()
    elif pilihan_menu == '2':
        data_siswa_tertentu()
    elif pilihan_menu == '3':
        print('''
    ** Anda Kembali ke Menu Utama **''')
        menu_utama()
    else:
        print()
        print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
        
        menu_data_siswa()

def data_seluruh_siswa():
        
        print('''
    ===============================================================
    --------- Database Nilai Ujian Siswa SD Tadika Mesra ----------
    ===============================================================''')
        print('''
    NIS\t\t| Nama\t| Bahasa Indonesia\t| Matematika\t| IPA''')
        for i, item in enumerate(daftar_nilai):
            print(f"\t{item['nis']}\t| {item['nama']}\t| {item['bahasa_indonesia']}\t\t\t\t| {item['matematika']}\t\t\t| {item['ipa']}")
        menu_data_siswa()

def data_siswa_tertentu():

    input_nis = int(input('''
    --| Cari Data Nilai Ujian Siswa
   ===============================================================
    Masukkan NIS Siswa yang Ingin Dicari: '''))

    for i in range(len(daftar_nilai)):
        if input_nis == daftar_nilai[i]['nis']:
            print(f'''
    ** Data Siswa dengan NIS "{input_nis}" Ditemukan **''')
            print('''
    ===============================================================
    --------- Database Nilai Ujian Siswa SD Tadika Mesra ----------
    ===============================================================''')
            print('''
    NIS\t\t| Nama\t| Bahasa Indonesia\t| Matematika\t| IPA''')
            print(f"\t{daftar_nilai[i]['nis']}\t| {daftar_nilai[i]['nama']}\t| {daftar_nilai[i]['bahasa_indonesia']}\t\t\t\t| {daftar_nilai[i]['matematika']}\t\t\t| {daftar_nilai[i]['ipa']}")
        
            menu_data_siswa()

    if input_nis != daftar_nilai[i]['nis']:
        print(f'''
    ** Data Siswa dengan NIS "{input_nis}" Tidak Ditemukan **''')
        
        menu_data_siswa()

# Function CREATE (Menambahkan Data Nilai Ujian Siswa)
# ====================================================

def input_data():
  
    print('''
    --| Silahkan Masukkan Data Siswa
    ===============================================================''')
    nis_siswa = int(input('\t1. Nomor Induk Siswa (NIS): '))
    for i in range(len(daftar_nilai)):
        if nis_siswa == daftar_nilai[i]['nis']:
          print('''
    ** Maaf, Data Sudah Ada **''')

          tambah_data()
          
        else:
            nama_siswa = input('\t2. Nama Siswa: ')
            nilai_bahasa = input('\t3. Nilai Bahasa Indonesia: ')
            nilai_mtk = input('\t4. Nilai Matematika: ')
            nilai_ipa = input('\t5. Nilai IPA: ')
            break

    konfirmasi = input('''
    --| Apakah Data Akan Disimpan (Y/N)? ''')
    if konfirmasi == 'Y' or konfirmasi == 'y':
        daftar_nilai.append({
                'nis': nis_siswa,
                'nama': nama_siswa,
                'bahasa_indonesia': nilai_bahasa,
                'matematika': nilai_mtk,
                'ipa': nilai_ipa
            })
        print('''
    ** Data Siswa Berhasil Ditambahkan **''')
        data_seluruh_siswa()
      
    elif konfirmasi == 'N' or konfirmasi == 'n':
        print('''
    ** Data Siswa Batal Ditambahkan **''')
    else:
        print()
        print('** Pilihan yang Anda Masukkan Salah **\n** Silahkan Masukkan Kembali Pilihan Anda **')

    tambah_data()

def tambah_data():
    
    while True:
        tambah_siswa = input('''
    ===============================================================
    --- Menu Penambahan Data Nilai Siswa --------------------------
    |-- Pilihan Menu:
        1. Tambah Data Nilai Siswa
        2. Kembali ke Menu Utama
    ===============================================================
    Silahkan Pilih Menu (1-2): ''')

        if tambah_siswa == '1':
            print()
            print('''
    -------------- Silahkan Masukkan Data Siswa  ---------------
    ===============================================================''')
            print('''
    --| Masukkan Informasi Siswa : ''')
            input_data()
        elif tambah_siswa == '2':
            print('''
        ** Anda Kembali ke Menu Utama **''')
            menu_utama()
        else:
            print()
        print('** Pilihan yang Anda Masukkan Salah **\n** Silahkan Masukkan Kembali Pilihan Anda **')
          
        input_data()

def tambah_data():
    
    while True:
        tambah_siswa = input('''
    ===============================================================
    --- Menu Input Data Nilai Siswa --------------------------
    |-- Pilihan Menu:
        1. Input Data Nilai Siswa
        2. Kembali ke Menu Utama
    ===============================================================
    Silahkan Pilih Menu (1-2): ''')

        if tambah_siswa == '1':
            print()
            print('''
    -------------- Silahkan Masukkan Data Siswa  ---------------
    ===============================================================''')
            print('''
    --| Masukkan Informasi Siswa: ''')
            input_data()
        elif tambah_siswa == '2':
            print('''
        |-- Anda Kembali ke Menu Utama''')
            menu_utama()
        else:
            print()
        print('** Pilihan yang Anda Masukkan Salah **\n** Silahkan Masukkan Kembali Pilihan Anda **')
       
        input_data()

def update_data():

    while True:
        update_data_siswa = input('''
    ===============================================================
    -------------- Menu Update Data Nilai Ujian Siswa -------------
    |-- Pilihan Menu:
        1. Update Data Nilai Siswa
        2. Kembali ke Menu Utama
    ===============================================================
    Silahkan Pilih Menu (1-2): ''')

        if update_data_siswa == '1':
            print('\t==========================================')
            nis_siswa = int(input('\t|-- Masukkan NIS Siswa yang Ingin Diupdate: '))
            for i in range(len(daftar_nilai)):
                  if nis_siswa == daftar_nilai[i]['nis']:
                    print('''
    ** Data Siswa Ditemukan **''')
                    konfirmasi = input('''
    --| Yakin Ingin Melanjutkan Update Data? (Y/N): ''')
                    print()
                    if konfirmasi == "Y" or konfirmasi == 'y':
                        print('''
    ** Lanjutkan Update Data **''')
                        keterangan = input('''
    ===============================================================
    ---------------- Menu Update Data Nilai Siswa -----------------
    --| Pilih Data yang Ingin Diubah:
        1. NIS Siswa
        2. Nama Siswa
        3. Nilai Bahasa Indonesia Siswa
        4. Nilai Matematika Siswa
        5. Nilai IPA Siswa
    ===============================================================
        Silahkan Pilih Menu (1-5): ''')
                        if keterangan == '1':
                            nis_baru = int(input('''
    --| Masukkan NIS Siswa yang Baru: '''))
                            konfirmasi_keterangan = input('''
    ** Apakah Yakin Akan Mengubah Data (Y/N)?: ''')
                            if konfirmasi_keterangan == 'Y' or konfirmasi_keterangan == 'y':
                                daftar_nilai[i]['nis'] = nis_baru
                                print('''
    ** Data Siswa Berhasil Diupdate *''')
                                data_seluruh_siswa()
                            elif konfirmasi_keterangan == 'N' or konfirmasi_keterangan == 'n':
                                print('''
    ** Batalkan Update Data **''')
                                update_data()
                            else:
                                print()
                                print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
                                break

                        elif keterangan == '2':
                            nama_baru = input('''
    --| Masukkan Nama Siswa yang Baru: ''')
                            konfirmasi_keterangan = input('''
    ** Apakah Yakin Akan Mengubah Data (Y/N)?: ''')
                            if konfirmasi_keterangan == 'Y' or konfirmasi_keterangan == 'y':
                                daftar_nilai[i]['nama'] = nama_baru
                                print('''
    ** Data Siswa Berhasil Diupdate **--------------''')
                                data_seluruh_siswa()

                            elif konfirmasi_keterangan == 'N' or konfirmasi_keterangan == 'n':
                                print('''
    ** Batalkan Update Data **''')
                                update_data()
                            else:
                                print()
                                print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
                                break

                        elif keterangan == '3':
                            nilai_bahasa_baru = input('''
    --| Masukkan Nilai Bahasa Indonesia yang Baru: ''')
                            konfirmasi_keterangan = input('''
    ** Apakah Yakin Akan Mengubah Data (Y/N)?: ''')
                            if konfirmasi_keterangan == 'Y' or konfirmasi_keterangan == 'y':
                                daftar_nilai[i]['bahasa_indonesia'] = nilai_bahasa_baru
                                print('''
    ** Data Siswa Berhasil Diupdate **''')
                                data_seluruh_siswa()

                            elif konfirmasi_keterangan == 'N' or konfirmasi_keterangan == 'n':
                                print('''
    ** Batalkan Update Data **''')
                                update_data_siswa()
                            else:
                                print()
                                print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
                                break

                        elif keterangan == '4':
                            nilai_mtk_baru = input('''
    --| Masukkan Nilai Matematika yang Baru: ''')
                            konfirmasi_keterangan = input('''
    ** Apakah Yakin Akan Mengubah Data (Y/N)?: ''')
                            if konfirmasi_keterangan == 'Y' or konfirmasi_keterangan == 'y':
                                daftar_nilai[i]['matematika'] = nilai_mtk_baru
                                print('''
     ** Data Siswa Berhasil Diupdate *''')
                                data_seluruh_siswa()

                            elif konfirmasi_keterangan == 'N' or konfirmasi_keterangan == 'n':
                                print('''
    ** Batalkan Update Data **''')
                                update_data()
                            else:
                                print()
                                print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
                                break

                        elif keterangan == '5':
                            nilai_ipa_baru = input('''
    --| Masukkan Nilai IPA yang Baru: ''')
                            konfirmasi_keterangan = input('''
    ** Apakah Yakin Akan Mengubah Data (Y/N)?: ''')
                            if konfirmasi_keterangan == 'Y' or konfirmasi_keterangan == 'y':
                                daftar_nilai[i]['ipa'] = nilai_ipa_baru
                                print('''
    ** Data Siswa Berhasil Diupdate **''')
                                data_seluruh_siswa()

                            elif konfirmasi_keterangan == 'N' or konfirmasi_keterangan == 'n':
                                print('''
    ** Batalkan Update Data **''')
                                update_data()
                            else:
                                print()
                                print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
                                break

                    elif konfirmasi == "N" or konfirmasi == 'n':
                        print('''
    ** Batalkan Update Data **''')
                        update_data()
                    else:
                        print()
                        print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
                        break

        elif update_data_siswa == '2':
            print('''
        |-- Anda Kembali ke Menu Utama''')
            menu_utama()
        else:
            print()
            print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
            update_data()


def hapus_data():

    while True:
        hapus_data_siswa = input('''
    ===============================================================
    -------------------- Menu Hapus Data Siswa --------------------
    |-- Pilihan Menu:
        1. Hapus Data Siswa
        2. Kembali ke Menu Utama
    ===============================================================
    Silahkan Pilih Menu (1-2): ''')

        if hapus_data_siswa == '1':
            nis_siswa = int(input('''
    ---| Masukkan NIS siswa yang ingin dihapus: '''))
            for i in range(len(daftar_nilai)):
                if nis_siswa == daftar_nilai[i]['nis']:
                    print('''
    ** Data Siswa Ditemukan **''')
                    konfirmasi_hapus_data = input('''
     ---| Apakah Yakin Ingin Menghapus Data (Y/N)?: ''')
                    if konfirmasi_hapus_data == 'Y' or konfirmasi_hapus_data == 'y':
                        nis_siswa == daftar_nilai [i]['nis']
                        del daftar_nilai[i]
                        print(f'''
    ** Data Siswa dengan NIS "{nis_siswa}" Berhasil Dihapus **''')
                        data_seluruh_siswa()
                    elif konfirmasi_hapus_data == 'N' or konfirmasi_hapus_data == 'n':
                        print('''
    ** Data Siswa Batal Dihapus **''')
                        break
                    else:
                        print()
                        print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
                        break

        elif hapus_data_siswa == '2':
            print('''
    ** Anda Kembali ke Menu Utama **''')
            menu_utama()

        else:
            print()
            print('\t** Pilihan yang Anda Masukkan Salah **\n\t** Silahkan Masukkan Kembali Pilihan Anda **')
            hapus_data()

def menu_utama ():
    pilihan_menu = input('''
    ===============================================================
    ---------- Database Nilai Ujian Siswa SD Tadika Mesra ---------
    ===============================================================
    |-- Pilihan Menu:
        1. Menampilkan Nilai Siswa
        2. Menginput Nilai Siswa
        3. Mengupdate Nilai Siswa
        4. Menghapus Nilai Siswa
        5. Keluar Dari Portal
    ===============================================================       
        Pilih Menu yang Ingin Dijalankan (1-5) : ''')
                
    if(pilihan_menu == '1') :
        menu_data_siswa()
    elif(pilihan_menu == '2') :
        input_data()
    elif(pilihan_menu == '3') :
        update_data()
    elif(pilihan_menu == '4') :
        hapus_data()
    elif(pilihan_menu == '5') :
        quit()
    else :
        print('Masukkan Angka Dengan Benar! (1-5)')
        menu_utama()

print(menu_utama())

